.\" Manpage for jmpd.
.\" Contact parabelboi@gmail.com to correct errors or typos.
.TH man 8 "18 Mar 2014" "1.2" "jmpd man page"
.SH NAME
jmpd \- Web Service GUI written in Java, utilizing Websockets and Bootstrap/JS
.SH SYNOPSIS
jmpd [OPTION]...
.SH DESCRIPTION
jmpd is a lightweight web client that runs within a jetty webserver. It's tuned for minimal resource usage and uses maven for revolving dependencies.

.SH BUGS
Probably.
.SH AUTHOR
Andrew Karpow (andy@ndyk.de)
.PP
Christian Krafft (parabelboi@gmail.com)
