.\" Manpage for ympc.
.\" Contact parabelboi@gmail.com to correct errors or typos.
.TH man 8 "18 Mar 2014" "1.2" "ympc man page"
.SH NAME
ympc \- Web Service GUI written in C, utilizing Bootstrap/JS
.SH SYNOPSIS
ympc [OPTION]...
.SH DESCRIPTION
ympc is a lightweight web client that runs without a dedicated webserver or interpreters like PHP, NodeJS or Ruby. It's tuned for minimal resource usage and requires only very litte dependencies.

ympc is based in part on the work of the mongoose http server (https://github.com/cesanta/mongoose)
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-url bootstrap url\fR
use alternative url to bootstrap services
.TP
\fB\-l\fR, \fB\-\-listen \[IP\]\:PORT\fR
listen on address, defaults to 127.0.0.1:8000
.TP
\fB\-u\fR, \fB\-\-user username\fR
drop privileges to the provided username after socket binding
.TP
\fB\-V\fR, \fB\-\-version\fR
print version and exit
.TP
\fB\-\-help\fR
print all valid options and exits
.SH BUGS
No known bugs.
.SH AUTHOR
Andrew Karpow (andy@ndyk.de)
.PP
Christian Krafft (parabelboi@gmail.com)
